#!/bin/bash

./section2grafo_peso Section01.txt
./section2grafo_peso Section02.txt
./section2grafo_peso Section03.txt
./section2grafo_peso Section04.txt
./section2grafo_peso Section05.txt
./section2grafo_peso Section06.txt
./section2grafo_peso Section07.txt
./section2grafo_peso Section08.txt
./section2grafo_peso Section09.txt
./section2grafo_peso Section10.txt
./section2grafo_peso Section11.txt
./section2grafo_peso Section12.txt
./section2grafo_peso Section13.txt
./section2grafo_peso Section14.txt
./section2grafo_peso Section15.txt
./section2grafo_peso Section16.txt
./section2grafo_peso Section17.txt
./section2grafo_peso Section18.txt
./section2grafo_peso Section19.txt
./section2grafo_peso Section20.txt
./section2grafo_peso Section21.txt
./section2grafo_peso Section22.txt
./section2grafo_peso Section23.txt
./section2grafo_peso Section24.txt
./section2grafo_peso Section25.txt
./section2grafo_peso Section26.txt
./section2grafo_peso Section27.txt
./section2grafo_peso Section28.txt
./section2grafo_peso Section29.txt
./section2grafo_peso Section30.txt
./section2grafo_peso Section31.txt
./section2grafo_peso Section32.txt
./section2grafo_peso Section33.txt
./section2grafo_peso Section34.txt
./section2grafo_peso Section35.txt
./section2grafo_peso Section36.txt
./section2grafo_peso Section37.txt
./section2grafo_peso Section38.txt
./section2grafo_peso Section39.txt
./section2grafo_peso Section40.txt
./section2grafo_peso Section41.txt
./section2grafo_peso Section42.txt
./section2grafo_peso Section43.txt
./section2grafo_peso Section44.txt
./section2grafo_peso Section45.txt
./section2grafo_peso Section46.txt
./section2grafo_peso Section47.txt
./section2grafo_peso Section48.txt
./section2grafo_peso Section49.txt
./section2grafo_peso Section50.txt
./section2grafo_peso Section51.txt
./section2grafo_peso Section52.txt
./section2grafo_peso Section53.txt
./section2grafo_peso Section54.txt
./section2grafo_peso Section55.txt
./section2grafo_peso Section56.txt
./section2grafo_peso Section57.txt
./section2grafo_peso Section58.txt
./section2grafo_peso Section59.txt
./section2grafo_peso Section60.txt
./section2grafo_peso Section61.txt
./section2grafo_peso Section62.txt
./section2grafo_peso Section63.txt
